# Prosper Loan Dataset Exploration
## by Ahmed Gharib

## Introduction
#### About Prosper

From the [Prosper](https://www.prosper.com/) website. Prosper was founded in 2005 as the first peer-to-peer lending marketplace in the United States. Since then, Prosper has facilitated more than $17 billion in loans to more than 1,030,000 people.

Through Prosper, people can invest in each other in a way that is financially and socially rewarding. Borrowers apply online for a fixed-rate, fixed-term loan between \\$2,000 and \\$40,000. Individuals and institutions can invest in the loans and earn attractive returns. Prosper handles all loan servicing on behalf of the matched borrowers and investors.

Prosper Marketplace is backed by leading investors including Sequoia Capital, Francisco Partners, Institutional Venture Partners, and Credit Suisse NEXT Fund.

### Table of Content
- [Preliminary Wrangling](#Wrangling)
- [Univariate Exploration](#UnivariateExploration)

<a id='Wrangling'></a>
## Preliminary Wrangling

[Prosper Loan Dataset](https://www.google.com/url?q=https://s3.amazonaws.com/udacity-hosted-downloads/ud651/prosperLoanData.csv&sa=D&ust=1602316069250000&usg=AOvVaw3v_Fjzy60OI_JxN1zu63ds) (Last update 03/11/2014)

- This dataset contains 113,937 loans with 81 variables on each loan, including loan amount, borrower rate (or interest rate), current loan status, borrower income, and many others.

- [This data dictionary](https://www.google.com/url?q=https://docs.google.com/spreadsheet/ccc?key%3D0AllIqIyvWZdadDd5NTlqZ1pBMHlsUjdrOTZHaVBuSlE%26usp%3Dsharing&sa=D&ust=1602316069252000&usg=AOvVaw30T5Cb1SJcH_-mM-PE6sWH) explains the variables in the data set.

In [1]:
# import all packages and set plots to be embedded inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Setting up the general theme of charts and color palette to use
sns.set_theme(style='white', palette='Set2')

# To display charts in the same notebook
%matplotlib inline

# Pandas diplay options
pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.set_option('display.float_format', lambda x: '%.5f' % x)

In [2]:
# First let's start by reading the data dictionary to understand each column of the data 
data_dict = pd.read_excel('data/Prosper Loan Data - Variable Definitions.xlsx')
data_dict

,Variable,Description
0,ListingKey,"Unique key for each listing, same value as the..."
1,ListingNumber,The number that uniquely identifies the listin...
2,ListingCreationDate,The date the listing was created.
3,CreditGrade,The Credit rating that was assigned at the tim...
4,Term,The length of the loan expressed in months.
5,LoanStatus,"The current status of the loan: Cancelled, Ch..."
6,ClosedDate,"Closed date is applicable for Cancelled, Compl..."
7,BorrowerAPR,The Borrower's Annual Percentage Rate (APR) fo...
8,BorrowerRate,The Borrower's interest rate for this loan.
9,LenderYield,The Lender yield on the loan. Lender yield is ...
10,EstimatedEffectiveYield,Effective yield is equal to the borrower inter...
11,EstimatedLoss,Estimated loss is the estimated principal loss...
12,EstimatedReturn,The estimated return assigned to the listing a...
13,ProsperRating (numeric),The Prosper Rating assigned at the time the l...
14,ProsperRating (Alpha),The Prosper Rating assigned at the time the li...
15,ProsperScore,A custom risk score built using historical Pro...
16,ListingCategory,The category of the listing that the borrower ...
17,BorrowerState,The two letter abbreviation of the state of th...
18,Occupation,The Occupation selected by the Borrower at the...
19,EmploymentStatus,The employment status of the borrower at the t...
20,EmploymentStatusDuration,The length in months of the employment status ...
21,IsBorrowerHomeowner,A Borrower will be classified as a homowner if...
22,CurrentlyInGroup,Specifies whether or not the Borrower was in a...
23,GroupKey,The Key of the group in which the Borrower is ...
24,DateCreditPulled,The date the credit profile was pulled.
25,CreditScoreRangeLower,The lower value representing the range of the ...
26,CreditScoreRangeUpper,The upper value representing the range of the ...
27,FirstRecordedCreditLine,The date the first credit line was opened.
28,CurrentCreditLines,Number of current credit lines at the time the...
29,OpenCreditLines,Number of open credit lines at the time the cr...
30,TotalCreditLinespast7years,Number of credit lines in the past seven years...
31,OpenRevolvingAccounts,Number of open revolving accounts at the time ...
32,OpenRevolvingMonthlyPayment,Monthly payment on revolving accounts at the t...
33,InquiriesLast6Months,Number of inquiries in the past six months at ...
34,TotalInquiries,Total number of inquiries at the time the cred...
35,CurrentDelinquencies,Number of accounts delinquent at the time the ...
36,AmountDelinquent,Dollars delinquent at the time the credit prof...
37,DelinquenciesLast7Years,Number of delinquencies in the past 7 years at...
38,PublicRecordsLast10Years,Number of public records in the past 10 years ...
39,PublicRecordsLast12Months,Number of public records in the past 12 months...
40,RevolvingCreditBalance,Dollars of revolving credit at the time the cr...
41,BankcardUtilization,The percentage of available revolving credit t...
42,AvailableBankcardCredit,The total available credit via bank card at th...
43,TotalTrades,Number of trade lines ever opened at the time ...
44,TradesNeverDelinquent,Number of trades that have never been delinque...
45,TradesOpenedLast6Months,Number of trades opened in the last 6 months a...
46,DebtToIncomeRatio,The debt to income ratio of the borrower at th...
47,IncomeRange,The income range of the borrower at the time t...
48,IncomeVerifiable,The borrower indicated they have the required ...
49,StatedMonthlyIncome,The monthly income the borrower stated at the ...
50,LoanKey,Unique key for each loan. This is the same key...
51,TotalProsperLoans,Number of Prosper loans the borrower at the ti...
52,TotalProsperPaymentsBilled,Number of on time payments the borrower made o...
53,OnTimeProsperPayments,Number of on time payments the borrower had ma...
54,ProsperPaymentsLessThanOneMonthLate,Number of payments the borrower made on Prospe...
55,ProsperPaymentsOneMonthPlusLate,Number of payments the borrower made on Prospe...
56,ProsperPrincipalBorrowed,Total principal borrowed on Prosper loans at t...
57,ProsperPrincipalOutstanding,Principal outstanding on Prosper loans at the ...
58,ScorexChangeAtTimeOfListing,Borrower's credit score change at the time the...
59,LoanCurrentDaysDelinquent,The number of days delinquent.
60,LoanFirstDefaultedCycleNumber,The cycle the loan was charged off. If the loa...
61,LoanMonthsSinceOrigination,Number of months since the loan originated.
62,LoanNumber,Unique numeric value associated with the loan.
63,LoanOriginalAmount,The origination amount of the loan.
64,LoanOriginationDate,The date the loan was originated.
65,LoanOriginationQuarter,The quarter in which the loan was originated.
66,MemberKey,The unique key that is associated with the bor...
67,MonthlyLoanPayment,The scheduled monthly loan payment.
68,LP_CustomerPayments,Pre charge-off cumulative gross payments made ...
69,LP_CustomerPrincipalPayments,Pre charge-off cumulative principal payments m...
70,LP_InterestandFees,Pre charge-off cumulative interest and fees pa...
71,LP_ServiceFees,Cumulative service fees paid by the investors ...
72,LP_CollectionFees,Cumulative collection fees paid by the investo...
73,LP_GrossPrincipalLoss,The gross charged off amount of the loan.
74,LP_NetPrincipalLoss,The principal that remains uncollected after a...
75,LP_NonPrincipalRecoverypayments,The interest and fee component of any recovery...
76,PercentFunded,Percent the listing was funded.
77,Recommendations,Number of recommendations the borrower had at ...
78,InvestmentFromFriendsCount,Number of friends that made an investment in t...
79,InvestmentFromFriendsAmount,Dollar amount of investments that were made by...
80,Investors,The number of investors that funded the loan.

In [3]:
# Loading the dataset and parsing the dates columns
date_columns = ['ListingCreationDate', 'ClosedDate', 'DateCreditPulled', 'FirstRecordedCreditLine', 'LoanOriginationDate']
loan = pd.read_csv('data/prosperLoanData.csv', parse_dates=date_columns)

In [4]:
# Display the shape of the data
loan.shape

(113937, 81)

In [5]:
# Display dataset summary statistics
loan.describe().T

,count,mean,std,min,25%,50%,75%,max
ListingNumber,113937.00000,627885.69251,328076.23639,4.00000,400919.00000,600554.00000,892634.00000,1255725.00000
Term,113937.00000,40.83025,10.43621,12.00000,36.00000,36.00000,36.00000,60.00000
BorrowerAPR,113912.00000,0.21883,0.08036,0.00653,0.15629,0.20976,0.28381,0.51229
BorrowerRate,113937.00000,0.19276,0.07482,0.00000,0.13400,0.18400,0.25000,0.49750
LenderYield,113937.00000,0.18270,0.07452,-0.01000,0.12420,0.17300,0.24000,0.49250
EstimatedEffectiveYield,84853.00000,0.16866,0.06847,-0.18270,0.11567,0.16150,0.22430,0.31990
EstimatedLoss,84853.00000,0.08031,0.04676,0.00490,0.04240,0.07240,0.11200,0.36600
EstimatedReturn,84853.00000,0.09607,0.03040,-0.18270,0.07408,0.09170,0.11660,0.28370
ProsperRating (numeric),84853.00000,4.07224,1.67323,1.00000,3.00000,4.00000,5.00000,7.00000
ProsperScore,84853.00000,5.95007,2.37650,1.00000,4.00000,6.00000,8.00000,11.00000
ListingCategory (numeric),113937.00000,2.77421,3.99680,0.00000,1.00000,1.00000,3.00000,20.00000
EmploymentStatusDuration,106312.00000,96.07158,94.48061,0.00000,26.00000,67.00000,137.00000,755.00000
CreditScoreRangeLower,113346.00000,685.56773,66.45827,0.00000,660.00000,680.00000,720.00000,880.00000
CreditScoreRangeUpper,113346.00000,704.56773,66.45827,19.00000,679.00000,699.00000,739.00000,899.00000
CurrentCreditLines,106333.00000,10.31719,5.45787,0.00000,7.00000,10.00000,13.00000,59.00000
OpenCreditLines,106333.00000,9.26016,5.02264,0.00000,6.00000,9.00000,12.00000,54.00000
TotalCreditLinespast7years,113240.00000,26.75454,13.63787,2.00000,17.00000,25.00000,35.00000,136.00000
OpenRevolvingAccounts,113937.00000,6.96979,4.63097,0.00000,4.00000,6.00000,9.00000,51.00000
OpenRevolvingMonthlyPayment,113937.00000,398.29216,447.15971,0.00000,114.00000,271.00000,525.00000,14985.00000
InquiriesLast6Months,113240.00000,1.43508,2.43751,0.00000,0.00000,1.00000,2.00000,105.00000
TotalInquiries,112778.00000,5.58440,6.42995,0.00000,2.00000,4.00000,7.00000,379.00000
CurrentDelinquencies,113240.00000,0.59205,1.97871,0.00000,0.00000,0.00000,0.00000,83.00000
AmountDelinquent,106315.00000,984.50706,7158.27016,0.00000,0.00000,0.00000,0.00000,463881.00000
DelinquenciesLast7Years,112947.00000,4.15498,10.16022,0.00000,0.00000,0.00000,3.00000,99.00000
PublicRecordsLast10Years,113240.00000,0.31265,0.72787,0.00000,0.00000,0.00000,0.00000,38.00000
PublicRecordsLast12Months,106333.00000,0.01509,0.15409,0.00000,0.00000,0.00000,0.00000,20.00000
RevolvingCreditBalance,106333.00000,17598.70675,32936.40179,0.00000,3121.00000,8549.00000,19521.00000,1435667.00000
BankcardUtilization,106333.00000,0.56131,0.31792,0.00000,0.31000,0.60000,0.84000,5.95000
AvailableBankcardCredit,106393.00000,11210.22545,19818.36131,0.00000,880.00000,4100.00000,13180.00000,646285.00000
TotalTrades,106393.00000,23.23003,11.87131,0.00000,15.00000,22.00000,30.00000,126.00000
TradesNeverDelinquent (percentage),106393.00000,0.88590,0.14818,0.00000,0.82000,0.94000,1.00000,1.00000
TradesOpenedLast6Months,106393.00000,0.80233,1.09764,0.00000,0.00000,0.00000,1.00000,20.00000
DebtToIncomeRatio,105383.00000,0.27595,0.55176,0.00000,0.14000,0.22000,0.32000,10.01000
StatedMonthlyIncome,113937.00000,5608.02557,7478.49728,0.00000,3200.33333,4666.66667,6825.00000,1750002.91667
TotalProsperLoans,22085.00000,1.42110,0.76404,0.00000,1.00000,1.00000,2.00000,8.00000
TotalProsperPaymentsBilled,22085.00000,22.93434,19.24958,0.00000,9.00000,16.00000,33.00000,141.00000
OnTimeProsperPayments,22085.00000,22.27195,18.83042,0.00000,9.00000,15.00000,32.00000,141.00000
ProsperPaymentsLessThanOneMonthLate,22085.00000,0.61363,2.44683,0.00000,0.00000,0.00000,0.00000,42.00000
ProsperPaymentsOneMonthPlusLate,22085.00000,0.04854,0.55629,0.00000,0.00000,0.00000,0.00000,21.00000
ProsperPrincipalBorrowed,22085.00000,8472.31196,7395.50765,0.00000,3500.00000,6000.00000,11000.00000,72499.00000
ProsperPrincipalOutstanding,22085.00000,2930.31391,3806.63508,0.00000,0.00000,1626.55000,4126.72000,23450.95000
ScorexChangeAtTimeOfListing,18928.00000,-3.22321,50.06357,-209.00000,-35.00000,-3.00000,25.00000,286.00000
LoanCurrentDaysDelinquent,113937.00000,152.81654,466.32025,0.00000,0.00000,0.00000,0.00000,2704.00000
LoanFirstDefaultedCycleNumber,16952.00000,16.26846,9.00590,0.00000,9.00000,14.00000,22.00000,44.00000
LoanMonthsSinceOrigination,113937.00000,31.89688,29.97418,0.00000,6.00000,21.00000,65.00000,100.00000
LoanNumber,113937.00000,69444.47427,38930.47961,1.00000,37332.00000,68599.00000,101901.00000,136486.00000
LoanOriginalAmount,113937.00000,8337.01385,6245.80058,1000.00000,4000.00000,6500.00000,12000.00000,35000.00000
MonthlyLoanPayment,113937.00000,272.47578,192.69781,0.00000,131.62000,217.74000,371.58000,2251.51000
LP_CustomerPayments,113937.00000,4183.07949,4790.90723,-2.34990,1005.76000,2583.83000,5548.40000,40702.39000
LP_CustomerPrincipalPayments,113937.00000,3105.53659,4069.52767,0.00000,500.89000,1587.50000,4000.00000,35000.00000
LP_InterestandFees,113937.00000,1077.54290,1183.41417,-2.34990,274.87000,700.84010,1458.54000,15617.03000
LP_ServiceFees,113937.00000,-54.72564,60.67542,-664.87000,-73.18000,-34.44000,-13.92000,32.06000
LP_CollectionFees,113937.00000,-14.24270,109.23276,-9274.75000,0.00000,0.00000,0.00000,0.00000
LP_GrossPrincipalLoss,113937.00000,700.44634,2388.51383,-94.20000,0.00000,0.00000,0.00000,25000.00000
LP_NetPrincipalLoss,113937.00000,681.42050,2357.16707,-954.55000,0.00000,0.00000,0.00000,25000.00000
LP_NonPrincipalRecoverypayments,113937.00000,25.14269,275.65794,0.00000,0.00000,0.00000,0.00000,21117.90000
PercentFunded,113937.00000,0.99858,0.01792,0.70000,1.00000,1.00000,1.00000,1.01250
Recommendations,113937.00000,0.04803,0.33235,0.00000,0.00000,0.00000,0.00000,39.00000
InvestmentFromFriendsCount,113937.00000,0.02346,0.23241,0.00000,0.00000,0.00000,0.00000,33.00000
InvestmentFromFriendsAmount,113937.00000,16.55075,294.54542,0.00000,0.00000,0.00000,0.00000,25000.00000
Investors,113937.00000,80.47523,103.23902,1.00000,2.00000,44.00000,115.00000,1189.00000

In [6]:
# Disply df info
loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113937 entries, 0 to 113936
Data columns (total 81 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   ListingKey                           113937 non-null  object
 1   ListingNumber                        113937 non-null  int64
 2   ListingCreationDate                  113937 non-null  datetime64[ns]
 3   CreditGrade                          28953 non-null   object
 4   Term                                 113937 non-null  int64
 5   LoanStatus                           113937 non-null  object
 6   ClosedDate                           55089 non-null   datetime64[ns]
 7   BorrowerAPR                          113912 non-null  float64
 8   BorrowerRate                         113937 non-null  float64
 9   LenderYield                          113937 non-null  float64
 10  EstimatedEffectiveYield              84853 non-null   float64
 11  EstimatedLoss                        84853 non-null   float64
 12  EstimatedReturn                      84853 non-null   float64
 13  ProsperRating (numeric)              84853 non-null   float64
 14  ProsperRating (Alpha)                84853 non-null   object
 15  ProsperScore                         84853 non-null   float64
 16  ListingCategory (numeric)            113937 non-null  int64
 17  BorrowerState                        108422 non-null  object
 18  Occupation                           110349 non-null  object
 19  EmploymentStatus                     111682 non-null  object
 20  EmploymentStatusDuration             106312 non-null  float64
 21  IsBorrowerHomeowner                  113937 non-null  bool
 22  CurrentlyInGroup                     113937 non-null  bool
 23  GroupKey                             13341 non-null   object
 24  DateCreditPulled                     113937 non-null  datetime64[ns]
 25  CreditScoreRangeLower                113346 non-null  float64
 26  CreditScoreRangeUpper                113346 non-null  float64
 27  FirstRecordedCreditLine              113240 non-null  datetime64[ns]
 28  CurrentCreditLines                   106333 non-null  float64
 29  OpenCreditLines                      106333 non-null  float64
 30  TotalCreditLinespast7years           113240 non-null  float64
 31  OpenRevolvingAccounts                113937 non-null  int64
 32  OpenRevolvingMonthlyPayment          113937 non-null  float64
 33  InquiriesLast6Months                 113240 non-null  float64
 34  TotalInquiries                       112778 non-null  float64
 35  CurrentDelinquencies                 113240 non-null  float64
 36  AmountDelinquent                     106315 non-null  float64
 37  DelinquenciesLast7Years              112947 non-null  float64
 38  PublicRecordsLast10Years             113240 non-null  float64
 39  PublicRecordsLast12Months            106333 non-null  float64
 40  RevolvingCreditBalance               106333 non-null  float64
 41  BankcardUtilization                  106333 non-null  float64
 42  AvailableBankcardCredit              106393 non-null  float64
 43  TotalTrades                          106393 non-null  float64
 44  TradesNeverDelinquent (percentage)   106393 non-null  float64
 45  TradesOpenedLast6Months              106393 non-null  float64
 46  DebtToIncomeRatio                    105383 non-null  float64
 47  IncomeRange                          113937 non-null  object
 48  IncomeVerifiable                     113937 non-null  bool
 49  StatedMonthlyIncome                  113937 non-null  float64
 50  LoanKey                              113937 non-null  object
 51  TotalProsperLoans                    22085 non-null   float64
 52  TotalProsperPaymentsBilled           22085 non-null   float64
 53  OnTimeProsperPayments                22085 non-null   float64
 54  ProsperPaymentsLessThanOneMonthLate  22085 non-null   float64
 55  ProsperPaymentsOneMonthPlusLate      22085 non-null   float64
 56  ProsperPrincipalBorrowed             22085 non-null   float64
 57  ProsperPrincipalOutstanding          22085 non-null   float64
 58  ScorexChangeAtTimeOfListing          18928 non-null   float64
 59  LoanCurrentDaysDelinquent            113937 non-null  int64
 60  LoanFirstDefaultedCycleNumber        16952 non-null   float64
 61  LoanMonthsSinceOrigination           113937 non-null  int64
 62  LoanNumber                           113937 non-null  int64
 63  LoanOriginalAmount                   113937 non-null  int64
 64  LoanOriginationDate                  113937 non-null  datetime64[ns]
 65  LoanOriginationQuarter               113937 non-null  object
 66  MemberKey                            113937 non-null  object
 67  MonthlyLoanPayment                   113937 non-null  float64
 68  LP_CustomerPayments                  113937 non-null  float64
 69  LP_CustomerPrincipalPayments         113937 non-null  float64
 70  LP_InterestandFees                   113937 non-null  float64
 71  LP_ServiceFees                       113937 non-null  float64
 72  LP_CollectionFees                    113937 non-null  float64
 73  LP_GrossPrincipalLoss                113937 non-null  float64
 74  LP_NetPrincipalLoss                  113937 non-null  float64
 75  LP_NonPrincipalRecoverypayments      113937 non-null  float64
 76  PercentFunded                        113937 non-null  float64
 77  Recommendations                      113937 non-null  int64
 78  InvestmentFromFriendsCount           113937 non-null  int64
 79  InvestmentFromFriendsAmount          113937 non-null  float64
 80  Investors                            113937 non-null  int64
dtypes: bool(3), datetime64[ns](5), float64(50), int64(11), object(12)
memory usage: 68.1+ MB

In [7]:
# Display the number of unique values for the string columns
loan.select_dtypes(include=['object']).nunique()

ListingKey                113066
CreditGrade                    8
LoanStatus                    12
ProsperRating (Alpha)          7
BorrowerState                 51
Occupation                    67
EmploymentStatus               8
GroupKey                     706
IncomeRange                    8
LoanKey                   113066
LoanOriginationQuarter        33
MemberKey                  90831
dtype: int64

In [8]:
# Display any duplicated values if any and the number of duplicates
print(f'number of duplicated rows: {loan[loan.duplicated()].shape[0]}')
loan[loan.duplicated()]

number of duplicated rows: 0

Empty DataFrame
Columns: [ListingKey, ListingNumber, ListingCreationDate, CreditGrade, Term, LoanStatus, ClosedDate, BorrowerAPR, BorrowerRate, LenderYield, EstimatedEffectiveYield, EstimatedLoss, EstimatedReturn, ProsperRating (numeric), ProsperRating (Alpha), ProsperScore, ListingCategory (numeric), BorrowerState, Occupation, EmploymentStatus, EmploymentStatusDuration, IsBorrowerHomeowner, CurrentlyInGroup, GroupKey, DateCreditPulled, CreditScoreRangeLower, CreditScoreRangeUpper, FirstRecordedCreditLine, CurrentCreditLines, OpenCreditLines, TotalCreditLinespast7years, OpenRevolvingAccounts, OpenRevolvingMonthlyPayment, InquiriesLast6Months, TotalInquiries, CurrentDelinquencies, AmountDelinquent, DelinquenciesLast7Years, PublicRecordsLast10Years, PublicRecordsLast12Months, RevolvingCreditBalance, BankcardUtilization, AvailableBankcardCredit, TotalTrades, TradesNeverDelinquent (percentage), TradesOpenedLast6Months, DebtToIncomeRatio, IncomeRange, IncomeVerifiable, StatedMonthlyIncome, LoanKey, TotalProsperLoans, TotalProsperPaymentsBilled, OnTimeProsperPayments, ProsperPaymentsLessThanOneMonthLate, ProsperPaymentsOneMonthPlusLate, ProsperPrincipalBorrowed, ProsperPrincipalOutstanding, ScorexChangeAtTimeOfListing, LoanCurrentDaysDelinquent, LoanFirstDefaultedCycleNumber, LoanMonthsSinceOrigination, LoanNumber, LoanOriginalAmount, LoanOriginationDate, LoanOriginationQuarter, MemberKey, MonthlyLoanPayment, LP_CustomerPayments, LP_CustomerPrincipalPayments, LP_InterestandFees, LP_ServiceFees, LP_CollectionFees, LP_GrossPrincipalLoss, LP_NetPrincipalLoss, LP_NonPrincipalRecoverypayments, PercentFunded, Recommendations, InvestmentFromFriendsCount, InvestmentFromFriendsAmount, Investors]
Index: []

In [9]:
# Number of loans for every year
loan.ListingCreationDate.dt.year.value_counts()

2013    35413
2012    19556
2007    11557
2011    11442
2008    11263
2014    10734
2006     6213
2010     5530
2009     2206
2005       23
Name: ListingCreationDate, dtype: int64

In [10]:
# Display the IncomeRange Value Counts
loan.IncomeRange.value_counts()

$25,000-49,999    32192
$50,000-74,999    31050
$100,000+         17337
$75,000-99,999    16916
Not displayed      7741
$1-24,999          7274
Not employed        806
$0                  621
Name: IncomeRange, dtype: int64

In [25]:
# Display Term Value Counts
loan.Term.value_counts()

36    87778
60    24545
12     1614
Name: Term, dtype: int64

In [26]:
# Display EmployementStatus Value Counts
loan.EmploymentStatus.value_counts()

Employed         67322
Full-time        26355
Self-employed     6134
Not available     5347
Other             3806
Part-time         1088
Not employed       835
Retired            795
Name: EmploymentStatus, dtype: int64

In [28]:
# Display ProsperScore Value Counts
loan.ProsperScore.value_counts().sort_index()

1.00000       992
2.00000      5766
3.00000      7642
4.00000     12595
5.00000      9813
6.00000     12278
7.00000     10597
8.00000     12053
9.00000      6911
10.00000     4750
11.00000     1456
Name: ProsperScore, dtype: int64

In [29]:
# Display a sample from where ProsperScore 11
loan[loan.ProsperScore == 11].sample(10)

,ListingKey,ListingNumber,ListingCreationDate,CreditGrade,Term,LoanStatus,ClosedDate,BorrowerAPR,BorrowerRate,LenderYield,EstimatedEffectiveYield,EstimatedLoss,EstimatedReturn,ProsperRating (numeric),ProsperRating (Alpha),ProsperScore,ListingCategory (numeric),BorrowerState,Occupation,EmploymentStatus,EmploymentStatusDuration,IsBorrowerHomeowner,CurrentlyInGroup,GroupKey,DateCreditPulled,CreditScoreRangeLower,CreditScoreRangeUpper,FirstRecordedCreditLine,CurrentCreditLines,OpenCreditLines,TotalCreditLinespast7years,OpenRevolvingAccounts,OpenRevolvingMonthlyPayment,InquiriesLast6Months,TotalInquiries,CurrentDelinquencies,AmountDelinquent,DelinquenciesLast7Years,PublicRecordsLast10Years,PublicRecordsLast12Months,RevolvingCreditBalance,BankcardUtilization,AvailableBankcardCredit,TotalTrades,TradesNeverDelinquent (percentage),TradesOpenedLast6Months,DebtToIncomeRatio,IncomeRange,IncomeVerifiable,StatedMonthlyIncome,LoanKey,TotalProsperLoans,TotalProsperPaymentsBilled,OnTimeProsperPayments,ProsperPaymentsLessThanOneMonthLate,ProsperPaymentsOneMonthPlusLate,ProsperPrincipalBorrowed,ProsperPrincipalOutstanding,ScorexChangeAtTimeOfListing,LoanCurrentDaysDelinquent,LoanFirstDefaultedCycleNumber,LoanMonthsSinceOrigination,LoanNumber,LoanOriginalAmount,LoanOriginationDate,LoanOriginationQuarter,MemberKey,MonthlyLoanPayment,LP_CustomerPayments,LP_CustomerPrincipalPayments,LP_InterestandFees,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors
58512,9C8B359476734939691165F,1028303,2013-11-23 07:00:43.953,NaN,60,Current,NaT,0.14147,0.11890,0.10890,0.10446,0.03740,0.06706,6.00000,A,11.00000,7,NC,Professional,Employed,39.00000,True,False,NaN,2013-11-23 07:00:44,700.00000,719.00000,2001-10-03,7.00000,4.00000,36.00000,3,61.00000,0.00000,1.00000,1.00000,4009.00000,0.00000,0.00000,0.00000,1894.00000,0.06000,27606.00000,27.00000,1.00000,1.00000,0.06000,"$75,000-99,999",True,7750.00000,997037005751981727C0E53,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,3,119690,8000,2013-12-04,Q4 2013,F0C8369969617248335EB70,177.51000,532.53000,300.73000,231.80000,-19.49000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,85
50672,FEB235923865115501DEA20,944372,2013-10-08 17:07:06.013,NaN,36,Current,NaT,0.06726,0.06050,0.05050,0.05001,0.00740,0.04261,7.00000,AA,11.00000,2,MS,Medical Technician,Employed,23.00000,True,False,NaN,2013-10-08 17:07:08,780.00000,799.00000,1999-02-01,7.00000,5.00000,21.00000,3,50.00000,1.00000,4.00000,0.00000,0.00000,0.00000,0.00000,0.00000,677.00000,0.03000,21423.00000,20.00000,1.00000,2.00000,0.08000,"$50,000-74,999",True,5750.00000,FA743694473285776DA8B8F,1.00000,13.00000,13.00000,0.00000,0.00000,7000.00000,0.82000,nan,0,nan,5,106348,6000,2013-10-16,Q4 2013,CD6A3552404040502BC1856,182.67000,730.68000,613.04000,117.64000,-19.46000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,136
69330,BF9335961531406546E46EE,1025068,2013-12-02 16:15:20.437,NaN,36,Current,NaT,0.09030,0.07690,0.06690,0.06546,0.01740,0.04806,7.00000,AA,11.00000,1,FL,Civil Service,Employed,141.00000,True,False,NaN,2013-12-02 16:15:26,720.00000,739.00000,1998-01-01,13.00000,10.00000,49.00000,12,393.00000,0.00000,1.00000,0.00000,0.00000,3.00000,0.00000,0.00000,55613.00000,0.51000,51987.00000,45.00000,1.00000,0.00000,0.18000,"$75,000-99,999",True,8000.00000,480A37000830872593338DF,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,3,121492,20000,2013-12-12,Q4 2013,494E3700061561763F55AFA,623.87000,1247.74000,989.72000,258.02000,-33.56000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,1
66887,CF633586582845136D54BCF,870435,2013-08-15 10:27:11.333,NaN,60,Current,NaT,0.15271,0.12990,0.11990,0.11477,0.03990,0.07487,6.00000,A,11.00000,1,OR,Accountant/CPA,Employed,74.00000,False,False,NaN,2013-09-26 00:58:16,700.00000,719.00000,1998-04-08,22.00000,22.00000,30.00000,8,392.00000,0.00000,4.00000,0.00000,0.00000,0.00000,1.00000,0.00000,10014.00000,0.79000,2175.00000,29.00000,1.00000,0.00000,0.26000,"$50,000-74,999",True,4179.16667,40EB369512347012520E111,2.00000,23.00000,23.00000,0.00000,0.00000,7000.00000,4271.50000,nan,0,nan,6,103730,15000,2013-09-30,Q3 2013,79B63531514994111789A51,341.22000,1700.76160,919.32000,781.44160,-60.57000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,1
105377,11163597070999520F7E95E,1103526,2013-12-22 12:41:49.253,NaN,36,Current,NaT,0.09030,0.07690,0.06690,0.06546,0.01740,0.04806,7.00000,AA,11.00000,1,CA,Architect,Employed,40.00000,True,False,NaN,2013-12-22 12:41:51,780.00000,799.00000,1997-09-01,19.00000,17.00000,33.00000,16,1010.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,27414.00000,0.16000,140836.00000,32.00000,1.00000,0.00000,0.25000,"$75,000-99,999",True,7083.33333,3E9B37013652115073802CA,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,3,123186,25000,2013-12-30,Q4 2013,7DB23702411395131202951,779.84000,1559.68000,1247.42000,312.26000,-40.60000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,491
106813,DC6E36001830095783330D9,1164885,2014-01-27 19:56:18.467,NaN,36,Current,NaT,0.08531,0.07160,0.06160,0.06044,0.01490,0.04554,7.00000,AA,11.00000,1,MA,Doctor,Employed,6.00000,False,False,NaN,2014-01-27 19:56:20,760.00000,779.00000,2006-03-13,13.00000,9.00000,19.00000,8,123.00000,2.00000,4.00000,0.00000,0.00000,0.00000,0.00000,0.00000,4.00000,0.00000,10746.00000,19.00000,1.00000,1.00000,0.12000,"$100,000+",True,16666.66667,4CEC37073689305497A1335,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,1,131802,16500,2014-02-19,Q1 2014,7F1835531369969696EB8A4,510.68000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,1
31244,C2253601924150768E9FC4D,1180475,2014-02-05 12:30:37.217,NaN,36,Current,NaT,0.13799,0.10990,0.09990,0.09628,0.03240,0.06388,6.00000,A,11.00000,1,OR,Teacher,Employed,89.00000,False,False,NaN,2014-02-05 12:30:40,680.00000,699.00000,2001-06-19,25.00000,25.00000,54.00000,6,201.00000,1.00000,1.00000,0.00000,0.00000,1.00000,0.00000,0.00000,6924.00000,0.69000,3076.00000,30.00000,0.93000,0.00000,0.19000,"$50,000-74,999",True,4333.33333,37D437068017203490B8686,1.00000,31.00000,31.00000,0.00000,0.00000,2000.00000,339.56000,nan,0,nan,1,131835,3975,2014-02-19,Q1 2014,53F234270310931715FA9EB,130.12000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,1
45561,968236026883765826C4F61,1153759,2014-02-11 08:59:22.640,NaN,60,Current,NaT,0.13659,0.11390,0.10390,0.09989,0.03490,0.06499,6.00000,A,11.00000,2,MN,Executive,Employed,196.00000,True,False,NaN,2014-02-11 08:59:25,800.00000,819.00000,1990-01-17,21.00000,20.00000,52.00000,17,462.00000,2.00000,3.00000,0.00000,0.00000,0.00000,0.00000,0.00000,3228.00000,0.04000,74627.00000,51.00000,0.94000,2.00000,0.18000,"$100,000+",True,14250.00000,D4B537064615322891F7C05,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,1,131298,35000,2014-02-13,Q1 2014,C6C43706548110837FCB20B,767.81000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,1
92307,AE563602421010579FA2AE7,1174594,2014-02-22 11:12:22.303,NaN,60,Current,NaT,0.09390,0.08090,0.07090,0.06919,0.01990,0.04929,7.00000,AA,11.00000,1,CA,Accountant/CPA,Employed,105.00000,True,False,NaN,2014-02-22 11:12:24,800.00000,819.00000,2001-12-28,16.00000,16.00000,22.00000,14,319.00000,0.00000,4.00000,0.00000,0.00000,0.00000,0.00000,0.00000,44077.00000,0.30000,99524.00000,21.00000,1.00000,0.00000,0.20000,"$50,000-74,999",True,4666.66667,B29937067449883668E512F,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,1,133777,14000,2014-02-25,Q1 2014,99183410916325451112231,284.47000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,1
36975,EA6A358839771588220FD89,901891,2013-09-17 03:50:00.993,NaN,60,Completed,2014-02-21,0.12113,0.09900,0.08900,0.08643,0.02490,0.06153,6.00000,A,11.00000,1,PA,Dentist,Employed,43.00000,True,False,NaN,2013-09-17 03:50:03,820.00000,839.00000,1980-02-02,8.00000,8.00000,30.00000,4,190.00000,0.00000,4.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1452.00000,0.03000,36798.00000,24.00000,1.00000,2.00000,0.13000,"$100,000+",True,16666.66667,29863693606992101A2D677,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,6,101670,22000,2013-09-19,Q3 2013,04723693084858781B7EA7F,466.35000,22837.90290,22000.00000,837.90290,-85.24000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,1

In [11]:
# Missing values from LoanStatus or BorrowerAPR
loan[['BorrowerAPR', 'LoanStatus']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113937 entries, 0 to 113936
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   BorrowerAPR  113912 non-null  float64
 1   LoanStatus   113937 non-null  object
dtypes: float64(1), object(1)
memory usage: 1.7+ MB

In [12]:
# Display the rows without APR rate
loan[loan['BorrowerAPR'].isnull()]

,ListingKey,ListingNumber,ListingCreationDate,CreditGrade,Term,LoanStatus,ClosedDate,BorrowerAPR,BorrowerRate,LenderYield,EstimatedEffectiveYield,EstimatedLoss,EstimatedReturn,ProsperRating (numeric),ProsperRating (Alpha),ProsperScore,ListingCategory (numeric),BorrowerState,Occupation,EmploymentStatus,EmploymentStatusDuration,IsBorrowerHomeowner,CurrentlyInGroup,GroupKey,DateCreditPulled,CreditScoreRangeLower,CreditScoreRangeUpper,FirstRecordedCreditLine,CurrentCreditLines,OpenCreditLines,TotalCreditLinespast7years,OpenRevolvingAccounts,OpenRevolvingMonthlyPayment,InquiriesLast6Months,TotalInquiries,CurrentDelinquencies,AmountDelinquent,DelinquenciesLast7Years,PublicRecordsLast10Years,PublicRecordsLast12Months,RevolvingCreditBalance,BankcardUtilization,AvailableBankcardCredit,TotalTrades,TradesNeverDelinquent (percentage),TradesOpenedLast6Months,DebtToIncomeRatio,IncomeRange,IncomeVerifiable,StatedMonthlyIncome,LoanKey,TotalProsperLoans,TotalProsperPaymentsBilled,OnTimeProsperPayments,ProsperPaymentsLessThanOneMonthLate,ProsperPaymentsOneMonthPlusLate,ProsperPrincipalBorrowed,ProsperPrincipalOutstanding,ScorexChangeAtTimeOfListing,LoanCurrentDaysDelinquent,LoanFirstDefaultedCycleNumber,LoanMonthsSinceOrigination,LoanNumber,LoanOriginalAmount,LoanOriginationDate,LoanOriginationQuarter,MemberKey,MonthlyLoanPayment,LP_CustomerPayments,LP_CustomerPrincipalPayments,LP_InterestandFees,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors
2543,044B3365298516680DA929B,36,2005-11-28 22:42:42.557,HR,36,Completed,2006-01-06,nan,0.10000,0.09500,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,5BE63365249159793785758,2005-11-28 22:42:42.557,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.02685,Not displayed,True,8333.33333,C1C4336516803221710615B,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,99,19,4200,2005-12-12,Q4 2005,10983364491040266AF6111,99.40000,4227.03000,4200.00000,27.03000,-4.02000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,5
14632,E4103364750435927B6F892,67,2006-01-06 12:54:51.887,AA,36,Completed,2006-04-10,nan,0.06500,0.05500,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,ACFB3365095848727895936,2006-01-06 12:54:51.887,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.09031,Not displayed,True,4166.66667,191C3365353954529711DE0,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,98,24,2620,2006-01-10,Q1 2006,12C53364471219226F478E8,80.30000,2657.72000,2620.00000,37.72000,-2.59000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,5
25166,B3083364738592238DBDA63,6,2005-11-15 16:06:47.457,AA,36,Completed,2005-11-29,nan,0.04350,0.03850,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,NaN,2005-11-15 16:06:47.457,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.04120,Not displayed,True,9166.66667,C29A3366376042420E5D6F4,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,100,5,1000,2005-11-23,Q4 2005,92263365124033374675E8D,29.68000,1000.72000,1000.00000,0.72000,-0.42000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,3
25330,B6C33364979883097BBCD77,39,2005-11-29 13:29:16.810,AA,36,Completed,2006-03-21,nan,0.06395,0.05520,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,BA973366260114148BF757A,2005-11-29 09:42:00.007,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.07707,Not displayed,True,7083.33333,A5A53366276781033D5C4FF,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,99,18,1500,2005-12-08,Q4 2005,D3213365072473957A40CF8,45.90000,1519.59000,1500.00000,19.59000,-1.30000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,4
29773,3480336511078238810A782,21,2005-11-18 14:48:19.753,AA,36,Completed,2008-06-05,nan,0.06000,0.05500,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,94E9336577086235891524E,2005-11-18 14:48:19.753,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.01923,Not displayed,True,8333.33333,44DA3365766842096917FF8,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,99,14,3000,2005-12-05,Q4 2005,0FE0336637558007610834C,91.27000,3203.37000,3000.00000,203.37000,-16.08000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,10
39870,B6E73366056348939D8801F,24,2005-11-20 14:45:55.193,C,36,Completed,2006-10-24,nan,0.12000,0.11500,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,12D7336581480170815332C,2005-11-20 14:45:55.193,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.29069,Not displayed,True,3333.33333,464E3365851398474A175A8,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,100,6,15000,2005-11-25,Q4 2005,B4183364632797286CA209B,498.21000,16445.53000,15000.00000,1445.53000,-53.96000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,6
43587,2F123364529418907A58D4C,19,2005-11-18 14:16:59.093,AA,36,Completed,2005-11-29,nan,0.08500,0.07500,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,NaN,2005-11-16 10:49:25.710,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.01510,Not displayed,True,18333.33333,051C3366339161583A81E4D,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,100,10,5000,2005-11-28,Q4 2005,4C9A3364566879406D66E65,157.84000,5001.10000,5000.00000,1.10000,-1.10000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,6
62297,2F25336514614362295DA03,7,2005-11-15 18:25:56.107,E,36,Completed,2005-11-30,nan,0.17000,0.11500,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,5BE63365249159793785758,2005-11-09 00:30:04.487,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.01783,Not displayed,True,10000.00000,81EF336558129564212843B,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,100,2,1000,2005-11-18,Q4 2005,0A8633658381202043D0226,35.65000,1003.95000,1000.00000,3.95000,-0.42000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,1
71280,DED033645500376547AF34E,60,2005-12-29 19:53:41.000,C,36,Completed,2008-04-21,nan,0.09000,0.08500,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,AD593366266318525BDAB73,2005-12-16 16:02:52.027,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.37002,Not displayed,True,7083.33333,05A133660705896823D1EF3,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,98,23,10000,2006-01-10,Q1 2006,F8E13365613650624A93FA5,318.00000,11349.06000,10000.00000,1349.06000,-74.98000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,8
71875,F50A33647261871547E3E0D,68,2006-01-06 13:05:50.890,AA,36,Completed,2006-07-11,nan,0.07000,0.06500,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,12D7336581480170815332C,2006-01-06 13:05:50.890,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.02343,Not displayed,True,4166.66667,84153365247069237E66630,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,98,25,3000,2006-01-10,Q1 2006,ED983364564478611B1273E,92.63000,3093.73000,3000.00000,93.73000,-6.01000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,1
73945,8D5F33655433257693D8033,18,2005-11-18 14:10:50.470,HR,36,Completed,2006-01-06,nan,0.25000,0.24500,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,NaN,2005-11-18 14:10:50.470,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.01234,Not displayed,True,29166.66667,9B343364431011460DD5847,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,100,4,2500,2005-11-22,Q4 2005,DDF8336636770758171C82D,99.40000,2576.56000,2500.00000,76.56000,-2.08000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,1
74114,0B4133652604109810CAA3B,34,2005-11-28 16:16:35.077,AA,36,Completed,2008-12-08,nan,0.06000,0.05500,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,NaN,2005-11-28 16:16:35.077,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.01115,Not displayed,True,9458.33333,32233364725508802D1C433,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,99,16,1000,2005-12-07,Q4 2005,5DDE33646556425236DA3CB,30.42000,1095.21000,1000.00000,95.21000,-7.61000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,7
75710,F7C53365521712881842072,25,2005-11-20 20:15:47.240,C,36,Completed,2005-11-30,nan,0.10000,0.07500,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,F0B53365823807576457B84,2005-11-16 11:25:26.897,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.09451,Not displayed,True,6666.66667,5B013365507761133BD470D,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,100,12,4000,2005-11-29,Q4 2005,A9FB3366058045381B7E12E,129.07000,4000.88000,4000.00000,0.88000,-0.88000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,3
78414,468C3366438848688B8B5B4,22,2005-11-18 16:35:48.210,AA,36,Completed,2006-01-09,nan,0.13000,0.12500,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,NaN,2005-11-17 15:13:19.920,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.01289,Not displayed,True,8333.33333,9B0C33664264358299699CB,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,100,3,2000,2005-11-22,Q4 2005,BF2C3365347545468EEC1DC,67.39000,2033.90000,2000.00000,33.90000,-1.68000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,2
80369,54A833661083301426FFC90,44,2005-12-03 14:03:22.207,AA,36,Completed,2006-01-06,nan,0.06500,0.05500,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,ACFB3365095848727895936,2005-11-28 10:19:33.010,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.09802,Not displayed,True,4166.66667,335E3365194260894C5E804,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,99,20,2689,2005-12-15,Q4 2005,12C53364471219226F478E8,82.42000,2698.72000,2689.00000,9.72000,-1.12000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,10
81848,584D3364403680278BB6704,28,2005-11-21 19:35:46.890,D,36,Completed,2008-03-18,nan,0.13000,0.09500,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,C846336482206839928D78F,2005-11-21 19:35:46.890,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.38380,Not displayed,True,1083.33333,732433648623176525D594A,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,100,8,4000,2005-11-28,Q4 2005,CDEF33658855538229DD0C5,88.12000,4705.19000,4000.00000,705.19000,-25.67000,-123.32290,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,4
90598,B87F3364623805558A45EAB,16,2005-11-18 13:39:03.263,B,36,Completed,2005-11-29,nan,0.12000,0.11500,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,NaN,2005-11-18 13:39:03.263,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.01051,Not displayed,True,16666.66667,979E3364988299845A2A448,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,100,9,1000,2005-11-28,Q4 2005,99443365049737429B8D4FC,33.21000,1000.33000,1000.00000,0.33000,-0.33000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,4
92516,80373365765621932269C34,48,2005-12-05 13:58:06.017,AA,36,Completed,2008-07-06,nan,0.07000,0.06500,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,B8143364846229046768A83,2005-12-05 13:58:06.017,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.04569,Not displayed,True,12500.00000,A1DA3366059246188A8B750,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,99,15,3500,2005-12-06,Q4 2005,D3123364665672102D89C63,0.00000,3793.45000,3500.00000,293.45000,-23.12000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,5
103509,0E0F336443449038617E9F4,59,2005-12-21 19:37:33.813,A,36,Completed,2008-12-30,nan,0.09450,0.08450,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,F63E33645133664151DBF61,2005-12-20 20:22:52.890,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.07015,Not displayed,True,12500.00000,11463365963100969351D1D,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,99,22,8998,2005-12-30,Q4 2005,6EC63364337535625235677,288.02000,10295.97000,8998.00000,1297.97000,-69.17000,0.00000,0.00000,0.00000,0.00000,1.01100,0,0,0.00000,14
105925,B01233643651103736EE3B6,20,2005-11-18 14:22:34.763,AA,36,Completed,2005-12-28,nan,0.08500,0.07500,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,F0B53365823807576457B84,2005-11-18 14:22:34.763,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.02743,Not displayed,True,6666.66667,EB8E3365902019869B4F403,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,100,11,5000,2005-11-28,Q4 2005,CAF83365574931485C12441,157.84000,5003.60000,5000.00000,3.60000,-2.38000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,6
106465,B8D63366141679436131B1C,23,2005-11-20 13:21:31.993,NC,36,Completed,2006-01-06,nan,0.09000,0.08500,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,12D7336581480170815332C,2005-11-09 12:01:07.900,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.03826,Not displayed,True,4166.66667,3FCC336526459619860F893,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,100,7,4800,2005-11-25,Q4 2005,ED983364564478611B1273E,152.64000,4849.36000,4800.00000,49.36000,-4.00000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,1
106735,97B333660731451030726AF,5,2005-11-11 08:46:17.303,AA,36,Completed,2006-02-07,nan,0.05950,0.05450,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,NaN,2005-11-11 08:46:17.303,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.01747,Not displayed,True,14583.33333,5FEA3365823284105CDF615,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,100,13,1500,2005-11-30,Q4 2005,BE4F33652072224311E37A5,45.60000,1516.58000,1500.00000,16.58000,-0.84000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,5
109027,F59D33647178242776CD53B,40,2005-11-29 20:23:22.770,AA,36,Completed,2006-01-06,nan,0.06000,0.05500,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,B8143364846229046768A83,2005-11-28 15:33:37.547,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.02217,Not displayed,True,25000.00000,AC4B33651299629964273AE,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,99,21,3000,2005-12-15,Q4 2005,6FB733664286679602C721D,0.00000,3010.85000,3000.00000,10.85000,-1.24000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,8
111607,84CC3365208034255DDCB47,35,2005-11-28 17:25:43.160,B,36,Completed,2005-12-08,nan,0.06500,0.06000,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,B8143364846229046768A83,2005-11-28 17:25:43.160,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.01404,Not displayed,True,16666.66667,31AC3364816494648054FCB,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,99,17,3000,2005-12-07,Q4 2005,B17A3365017647637E14A1C,91.95000,3000.53000,3000.00000,0.53000,-0.53000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,5
113921,D21A33647075665665BE266,4,2005-11-09 20:44:28.847,AA,36,Completed,2005-11-25,nan,0.04000,0.03500,nan,nan,nan,nan,NaN,nan,0,NaN,NaN,NaN,nan,False,False,B8143364846229046768A83,2005-11-09 20:44:28.847,nan,nan,NaT,nan,nan,nan,0,0.00000,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.23284,Not displayed,True,12500.00000,30FD3365652573455326F15,nan,nan,nan,nan,nan,nan,nan,nan,0,nan,100,1,1000,2005-11-15,Q4 2005,D3123364665672102D89C63,29.52000,1000.89000,1000.00000,0.89000,-0.88000,0.00000,0.00000,0.00000,0.00000,1.00000,0,0,0.00000,1

### What is the structure of your dataset?

There are 113,937 observations for prosper loans with 81 features most features are numeric in type (61) float64(50), int64(11), bool(3), datetime64\[ns](5),  object(12)

### What is/are the main feature(s) of interest in your dataset?

Mainly interested in 2 features BorrowerAPR and LoanStatus to help me answer the following questions:
- What factors affect a loan’s outcome status?
- What affects the borrower’s APR or interest rate? 
- Are there differences between loans depending on how large the original loan amount was?

### What features in the dataset do you think will help support your investigation into your feature(s) of interest?


|Variable|Description|
|---|---|
|ListingCreationDate|	The date the listing was created|
|Term|	The length of the loan expressed in months|
|LoanStatus|	The current status of the loan: Cancelled,  Chargedoff, Completed, Current, Defaulted, FinalPaymentInProgress, PastDue. The PastDue status will be accompanied by a delinquency bucket|
|BorrowerAPR|	The Borrower's Annual Percentage Rate (APR) for the loan|
|ProsperRating| (Alpha)	The Prosper Rating assigned at the time the listing was created between AA - HR.  Applicable for loans originated after July 2009|
|ProsperScore|	A custom risk score built using historical Prosper data. The score ranges from 1-10, with 10 being the best, or lowest risk score.  Applicable for loans originated after July 2009|
|ListingCategory|	The category of the listing that the borrower selected when posting their listing: 0 - Not Available, 1 - Debt Consolidation, 2 - Home Improvement, 3 - Business, 4 - Personal Loan, 5 - Student Use, 6 - Auto, 7- Other, 8 - Baby&Adoption, 9 - Boat, 10 - Cosmetic Procedure, 11 - Engagement Ring, 12 - Green Loans, 13 - Household Expenses, 14 - Large Purchases, 15 - Medical/Dental, 16 - Motorcycle, 17 - RV, 18 - Taxes, 19 - Vacation, 20 - Wedding Loans|
|BorrowerState|	The two letter abbreviation of the state of the address of the borrower at the time the Listing was created|
|Occupation|	The Occupation selected by the Borrower at the time they created the listing|
|EmploymentStatus|	The employment status of the borrower at the time they posted the listing|
|EmploymentStatusDuration|	The length in months of the employment status at the time the listing was created|
|IsBorrowerHomeowner|	A Borrower will be classified as a homowner if they have a mortgage on their credit profile or provide documentation confirming they are a homeowner|
|CreditScoreRangeLower|	The lower value representing the range of the borrower's credit score as provided by a consumer credit rating agency|
|CreditScoreRangeUpper|	The upper value representing the range of the borrower's credit score as provided by a consumer credit rating agency|
|IncomeRange|	The income range of the borrower at the time the listing was created|
|OnTimeProsperPayments|	Number of on time payments the borrower had made on Prosper loans at the time they created this listing. This value will be null if the borrower has no prior loans|
|LoanCurrentDaysDelinquent|	The number of days delinquent|
|LoanOriginalAmount|	The origination amount of the loan|
|Recommendations|	Number of recommendations the borrower had at the time the listing was created|

Before I close this section let's do some data cleaning 
- Chose a subset of the data to work with to include just the columns of intrest.
- Rename the ProsperRating (Alpha) and ListingCategory (numeric) columns.
- Replace the numbers of ListingCategory to Categories.
- Convert the categorical columns into categorical dtype .
- Drop rows with missing APR values.
- Drop data from 2005 and 2014 as they are not complete.

In [13]:
# List of columns to use with the features of intrest
use_cols = ['ListingCreationDate',
            'Term',
            'LoanStatus', 
            'BorrowerAPR', 
            'ProsperRating (Alpha)', 
            'ProsperScore', 
            'ListingCategory (numeric)', 
            'BorrowerState', 
            'Occupation', 
            'EmploymentStatus', 
            'EmploymentStatusDuration', 
            'IsBorrowerHomeowner', 
            'CreditScoreRangeLower', 
            'CreditScoreRangeUpper', 
            'IncomeRange', 
            'OnTimeProsperPayments', 
            'LoanCurrentDaysDelinquent', 
            'LoanOriginalAmount', 
            'Recommendations']

In [14]:
# Copy of the data frame to clean it
loan_clean = loan.copy()

# Use only the columns of intrest
loan_clean = loan_clean[use_cols]

# drop the data of 2005 and 2014
loan_clean = loan_clean.loc[~loan_clean.ListingCreationDate.dt.year.isin([2005, 2014])].reset_index().drop('index', axis=1)

In [19]:
# Drop rows with no APR values
loan_clean = loan_clean.loc[~loan_clean['BorrowerAPR'].isnull()].reset_index().drop('index', axis=1)

In [20]:
# Rename the ProsperRating (Alpha) and ListingCategory (numeric) columns
loan_clean = loan_clean.rename(columns={'ProsperRating (Alpha)': 'ProsperRating',
                                        'ListingCategory (numeric)': 'ListingCategory'})

In [21]:
# Replace the numbers of ListingCategory to Categories
listing_category_dict = {0: 'Not Available',
                         1: 'Debt Consolidation', 
                         2: 'Home Improvement', 
                         3: 'Business', 
                         4: 'Personal Loan', 
                         5: 'Student Use', 
                         6: 'Auto',
                         7: 'Other', 
                         8: 'Baby&Adoption', 
                         9: 'Boat', 
                         10: 'Cosmetic Procedure', 
                         11: 'Engagement Ring', 
                         12: 'Green Loans', 
                         13: 'Household Expenses', 
                         14: 'Large Purchases', 
                         15: 'Medical/Dental', 
                         16: 'Motorcycle', 
                         17: 'RV', 
                         18: 'Taxes', 
                         19: 'Vacation',
                         20: 'Wedding Loans'}

loan_clean.ListingCategory.replace(listing_category_dict, inplace=True)

In [30]:
# Dictionary of ordered categories
cat_dict = {'ProsperRating': ['AA', 'A', 'B', 'C', 'D', 'E', 'HR'],
            'IncomeRange': ['$100,000+', '$75,000-99,999', '$50,000-74,999', '$25,000-49,999', 
                            '$1-24,999', '$0', 'Not displayed', 'Not employed'],
            'Term': [60, 36, 12]}

# List of columns to convert
cat_cols = ['EmploymentStatus', 'LoanStatus', 'ListingCategory', 'BorrowerState', 'Occupation']

In [32]:
# Converting ordered categories columns 

for col in cat_dict:
    ordered_cat = pd.api.types.CategoricalDtype(ordered = True,
                                                categories = cat_dict[col])
    loan_clean[col] = loan_clean[col].astype(ordered_cat)

In [33]:
# Converting other categorical clomuns

for col in cat_cols:
    loan_clean[col] = loan_clean[col].astype('category')

In [34]:
loan_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 103178 entries, 0 to 103179
Data columns (total 19 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   ListingCreationDate        103178 non-null  datetime64[ns]
 1   Term                       103178 non-null  category
 2   LoanStatus                 103178 non-null  category
 3   BorrowerAPR                103178 non-null  float64
 4   ProsperRating              74119 non-null   category
 5   ProsperScore               74119 non-null   float64
 6   ListingCategory            103178 non-null  category
 7   BorrowerState              97688 non-null   category
 8   Occupation                 100137 non-null  category
 9   EmploymentStatus           100948 non-null  category
 10  EmploymentStatusDuration   95578 non-null   float64
 11  IsBorrowerHomeowner        103178 non-null  bool
 12  CreditScoreRangeLower      102612 non-null  float64
 13  CreditScoreRangeUpper      102612 non-null  float64
 14  IncomeRange                103178 non-null  category
 15  OnTimeProsperPayments      21008 non-null   float64
 16  LoanCurrentDaysDelinquent  103178 non-null  int64
 17  LoanOriginalAmount         103178 non-null  int64
 18  Recommendations            103178 non-null  int64
dtypes: bool(1), category(8), datetime64[ns](1), float64(6), int64(3)
memory usage: 9.6 MB

<a id='UnivariateExploration'></a>
## Univariate Exploration

> In this section, investigate distributions of individual variables. If
you see unusual points or outliers, take a deeper look to clean things up
and prepare yourself to look at relationships between variables.

> Make sure that, after every plot or related series of plots, that you
include a Markdown cell with comments about what you observed, and what
you plan on investigating next.

### Discuss the distribution(s) of your variable(s) of interest. Were there any unusual points? Did you need to perform any transformations?

> Your answer here!

### Of the features you investigated, were there any unusual distributions? Did you perform any operations on the data to tidy, adjust, or change the form of the data? If so, why did you do this?

> Your answer here!

## Bivariate Exploration

> In this section, investigate relationships between pairs of variables in your
data. Make sure the variables that you cover here have been introduced in some
fashion in the previous section (univariate exploration).

### Talk about some of the relationships you observed in this part of the investigation. How did the feature(s) of interest vary with other features in the dataset?

> Your answer here!

### Did you observe any interesting relationships between the other features (not the main feature(s) of interest)?

> Your answer here!

## Multivariate Exploration

> Create plots of three or more variables to investigate your data even
further. Make sure that your investigations are justified, and follow from
your work in the previous sections.

### Talk about some of the relationships you observed in this part of the investigation. Were there features that strengthened each other in terms of looking at your feature(s) of interest?

> Your answer here!

### Were there any interesting or surprising interactions between features?

> Your answer here!

> At the end of your report, make sure that you export the notebook as an
html file from the `File > Download as... > HTML` menu. Make sure you keep
track of where the exported file goes, so you can put it in the same folder
as this notebook for project submission. Also, make sure you remove all of
the quote-formatted guide notes like this one before you finish your report!